@props(['action', 'method' => 'POST', 'employee' => null, 'positions' => ['Rep', 'RM', 'FFM']])

<form action="{{ $action }}" method="POST" class="space-y-4">
    @csrf
    @if($method !== 'POST')
        @method($method)
    @endif

    <div>
        <label for="full_name" class="block text-sm font-medium text-gray-600">Full Name</label>
        <input name="full_name" type="text" placeholder="Full Name" value="{{ old('full_name', $employee->full_name ?? '') }}"
               class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
    </div>
    <div>
        <label for="first_name" class="block text-sm font-medium text-gray-600">First Name</label>
        <input name="first_name" id="first_name" type="text" placeholder="First Name" value="{{ old('first_name', $employee->first_name ?? '') }}"
               class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" oninput="generateEmail()">
    </div>
    <div>
        <label for="last_name" class="block text-sm font-medium text-gray-600">Last Name</label>
        <input name="last_name" id="last_name" type="text" placeholder="Last Name" value="{{ old('last_name', $employee->last_name ?? '') }}"
               class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" oninput="generateEmail()">
    </div>
    <div>
        <label for="birth_date" class="block text-sm font-medium text-gray-600">Birth Date</label>
        <input name="birth_date" type="date" value="{{ old('birth_date', $employee->birth_date ?? '') }}"
               class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
    </div>
    <div>
        <label for="email" class="block text-sm font-medium text-gray-600">Email</label>
        <input name="email" id="email" type="email" placeholder="Email"
               value="{{ old('email', $employee->email ?? '') }}"
               class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
               data-auto-generated="true">
    </div>
    <div>
        <label for="hiring_date" class="block text-sm font-medium text-gray-600">Hiring Date</label>
        <input name="hiring_date" type="date"
        {{-- value="{{ old('hiring_date', $employee->hiring_date ?? '') }}" --}}
        value="{{now()->format("Y-m-d")}}"
               class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
    </div>
    <div>
        <label for="position" class="block text-sm font-medium text-gray-600">Position</label>
        <select name="position" id="position"
                class="w-full p-3 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            @foreach($positions as $position)
                <option value="{{ $position }}" {{ old('position', $employee->position ?? '') === $position ? 'selected' : '' }}>
                    {{ $position }}
                </option>
            @endforeach
        </select>
    </div>
    <div class="flex justify-end">
        <button type="submit"
                class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-3 px-6 rounded-lg transition duration-300">
            {{ $employee ? 'Edit' : 'Create' }}
        </button>
    </div>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const firstNameInput = document.getElementById("first_name");
        const lastNameInput = document.getElementById("last_name");
        const emailInput = document.getElementById("email");

        function generateEmail() {
            if (emailInput.dataset.autoGenerated === "false") return; // Если email изменен вручную, не перезаписываем

            let firstName = firstNameInput.value.trim().toLowerCase();
            let lastName = lastNameInput.value.trim().toLowerCase();

            if (firstName && lastName) {
                emailInput.value = `${firstName}.${lastName}@nobel.kz`;
            }
        }

        firstNameInput.addEventListener("input", generateEmail);
        lastNameInput.addEventListener("input", generateEmail);

        emailInput.addEventListener("focus", () => {
            emailInput.dataset.autoGenerated = "false"; // Если пользователь нажал на поле email, автогенерация отключается
        });
    });
</script>
