# version: "3.8"

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        ports:
            - "8000:80"

    db:
        image: mysql:8
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
